global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gpu-exporter
    scrape_interval: 1s
    scrape_timeout: 900ms
    metrics_path: /metrics
    static_configs:
      - targets:
          - gpu-exporter:9990
